SCR_ConfigurableDialogUiPresets {
 m_aPresets {
  SCR_ConfigurableDialogUiPreset "{68D70CFD0FB74C5D}" {
   m_sTag "server_rules"
   m_aButtons {
    SCR_ConfigurableDialogUiButtonPreset "{68D70CFC18C140CB}" {
     m_sTag "confirm"
     m_sActionName "DialogConfirm"
     m_sLabel "#AR-Button_Confirm-UC"
     m_eAlign RIGHT
    }
    SCR_ConfigurableDialogUiButtonPreset "{68D70CFC1FA8ACBD}" {
     m_sTag "cancel"
     m_sActionName "MenuBack"
     m_sLabel "#AR-Workshop_ButtonCancel"
    }
   }
  }
  SCR_ConfigurableDialogUiPreset "{68D4C7B64272AD63}" {
   m_sLayout "{604721ED8E6ED459}UI/layouts/Menus/Dialogs/ConfigurableDialog_Big.layout"
   m_sTag "server_rules_large"
   m_sTitleIconImageName "join"
   m_aButtons {
    SCR_ConfigurableDialogUiButtonPreset "{68D4C7B6C8E7A90A}" {
     m_sTag "confirm"
     m_sActionName "DialogConfirm"
     m_sLabel "#AR-Button_Confirm-UC"
     m_eAlign RIGHT
    }
    SCR_ConfigurableDialogUiButtonPreset "{68D4C7B6C935F80D}" {
     m_sTag "cancel"
     m_sActionName "MenuBack"
     m_sLabel "#AR-Workshop_ButtonCancel"
    }
   }
  }
 }
}